Add vagga integration
kpi-web-guild/django-girls-blog-DrEdi pull request #19
Opened 2017-01-04 10:52 UTC by DrEdi

Integrate with vagga. Change main DB to sqlite

2017-01-04 13:20 UTC, webknjaz requested changes
with `django-environ` you don't need local_settings anymore.
also BASE_DIR, DATABASES and DEBUG vars should be taken from env vars with some explicit defaults.

2017-01-04 13:20 UTC, webknjaz commented on blog/settings.py
> +    'default':  env.db()
please add explicit default here. (See PEP20: Explicit is better than implicit. (c) Zen of Python)

2017-01-04 13:20 UTC, webknjaz commented on vagga.yaml
> +        dependencies: true
this is not needed for freeze container, since it will result in writing implicit dependencies to requirements.

2017-01-04 13:20 UTC, webknjaz commented on vagga.yaml
> +    setup:
`dependencies: true` is required for this container though.

2017-01-04 13:20 UTC, webknjaz commented on requirements.txt
> +six==1.10.0
This is not needed

2017-01-04 13:20 UTC, webknjaz commented on requirements.txt
> -psycopg2==2.6.2
I'd move it to separate prod config

2017-01-04 19:34 UTC, DrEdi commented on requirements.txt
> +six==1.10.0
This line is automatically written by pip-freeze
And if i'm not wrong - this is dependency for django-environ

`ImportError: No module named 'six'`

2017-01-04 20:27 UTC, webknjaz requested changes
Also I remind you to remove unnecessary imports in the bottom of `settings.py`

2017-01-04 20:27 UTC, webknjaz commented on requirements.txt
> +six==1.10.0
Regenerate it.

2017-01-04 20:27 UTC, webknjaz commented on blog/settings.py
> +root = environ.Path(__file__) - 3
I would call it `root_dir`/`base_dir`. Also, you should not forget to read `.env` file contents into environment (don't forget to gitignore it). See example at: https://github.com/open-craft-guild/crm-smsfly/blob/master/SMSFlyCRM/settings.py#L21

2017-01-04 20:27 UTC, webknjaz commented on blog/settings.py
>  SECRET_KEY = 'u1^ao$3(lwk%g+i6+_)-e(1-f%^56dqq&0$*zlugavt!=es@r4'
This should also be read from env

2017-01-04 20:27 UTC, webknjaz commented on blog/settings.py
> +    'extra': env.db('SQLITE_URL', default='sqlite:///db.sqlite3')
I think, `default` is enough, just set `default='sqlite:///db.sqlite3'` for it.

2017-01-04 20:27 UTC, webknjaz commented on blog/settings.py
> +STATIC_URL = 'static/'
Why did you do this?

2017-01-04 20:27 UTC, webknjaz commented on blog/settings.py
>  STATIC_ROOT = os.path.join(BASE_DIR, 'static')
with `Path()` imported you may use it for concatenation now

2017-01-04 20:27 UTC, webknjaz commented on vagga.yaml
> +      - !Alpine v3.4
the distro definition is usually put first

2017-01-04 21:16 UTC, DrEdi commented on blog/settings.py
> +STATIC_URL = 'static/'
accidentally, sorry
I didn't see

2017-01-05 04:50 UTC, webknjaz requested changes
Have you checked that it's really working with these changes?

2017-01-05 04:50 UTC, webknjaz commented on .gitignore
> +#Django-env
it's called dotenv

2017-01-05 04:50 UTC, webknjaz commented on blog/settings.py
> +SECRET_KEY = env('SECRET_KEY')
leave a default as a fallback for development

2017-01-05 04:50 UTC, webknjaz commented on blog/settings.py
> +STATIC_ROOT = env.path('STATIC_ROOT', BASE_DIR('static'))
does this actually work?

2017-01-05 04:50 UTC, webknjaz commented on vagga.yaml
> +      DATABASE_URL: sqlite:///db.sqlite3
Currently, you don't really need this as it's a default. You'll need to specify it in your next PR exposing postgres support

2017-01-06 12:18 UTC, webknjaz commented on vagga.yaml
> +        - Django
Normally you would need to lock some range of versions, because major version change may introduce backward incompatible changes.

2017-01-06 12:22 UTC, webknjaz commented on vagga.yaml
> +        - Django
https://github.com/open-craft-guild/crm-smsfly/blob/master/vagga.yaml#L25-L27

2017-01-06 12:25 UTC, DrEdi commented on vagga.yaml
> +        - Django
and it's required for all dependencies?

2017-01-06 12:26 UTC, webknjaz commented on vagga.yaml
> +        - Django
most of. I think you don't really need to lock pip

2017-01-06 12:30 UTC, webknjaz commented on .gitignore
>  #PyCharm
it is a good practice to have space after the hash

2017-01-06 12:57 UTC, DrEdi commented on vagga.yaml
> +        - Django
ok, catched it

2017-01-06 13:07 UTC, webknjaz requested changes

2017-01-06 13:07 UTC, webknjaz commented on vagga.yaml
> +        - 'gunicorn >=19.5,<=16.6.0'
this doesn't make sense. you didn't try running it.

2017-01-06 13:07 UTC, webknjaz commented on vagga.yaml
> +        - 'Django >= 1.9,<=1.10.5'
it's insane, why would you restrict patch version?

2017-01-06 13:07 UTC, webknjaz commented on vagga.yaml
> +        - 'whitenoise >= 3.2,<=3.2.3'
doesn't make sense inside of same minor version

2017-01-06 13:07 UTC, webknjaz commented on vagga.yaml
> +        - 'django-environ >= 0.4,<=0.4.1'
doesn't make sense as doesn't allow upgrading patch versions

2017-01-06 13:19 UTC, DrEdi commented on vagga.yaml
> +        - 'django-environ >= 0.4,<=0.4.1'
Hmm...
But what if in next realize will be something that broke my system? (comment a bit higher)
I don't really know all the features in each version

2017-01-06 13:21 UTC, webknjaz commented on vagga.yaml
> +        - 'django-environ >= 0.4,<=0.4.1'
http://semver.org/#semantic-versioning-200

2017-01-06 13:22 UTC, DrEdi commented on vagga.yaml
> +        - 'gunicorn >=19.5,<=16.6.0'
16.6.0 had to be 19.6.0  :0

2017-01-06 13:26 UTC, DrEdi commented on vagga.yaml
> +        - 'django-environ >= 0.4,<=0.4.1'
ok
so it'd be better to write for example 
gunicorn >=19.5,<=19.6.0'
'whitenoise >= 3.2,<=3.3'
'django-environ >= 0.4,<=0.5'

right?

2017-01-06 13:31 UTC, webknjaz commented on vagga.yaml
> +        - 'django-environ >= 0.4,<=0.4.1'
yes.

> 19.6.0
trailing `0` is not necessary here

2017-01-06 13:32 UTC, webknjaz commented on vagga.yaml
> +        - 'django-environ >= 0.4,<=0.4.1'
and keep the same/single style of placing whitespaces

2017-01-06 19:32 UTC, klochenok approved these changes

2017-01-06 19:39 UTC, webknjaz commented on vagga.yaml
> +        - 'Django >= 1.9,<=1.10.5'
still?

2017-01-06 19:39 UTC, webknjaz commented on vagga.yaml
> +        - 'Django >= 1.9,<=1.10.5'
also mind using consistent spacing

2017-01-06 19:58 UTC, DrEdi commented on vagga.yaml
> +        - 'Django >= 1.9,<=1.10.5'
oooops

2017-01-06 20:14 UTC, webknjaz requested changes
Please rewrite this branch commits removing garbage and squashing them into atomic ones. Also before pushing check that everything is being built/run correctly.

2017-01-06 20:15 UTC, webknjaz commented on requirements.txt
> +Django==1.10
I think, there is no such version of Django existing.

2017-01-06 20:16 UTC, webknjaz commented on vagga.yaml
> +        - 'Django >=1.9,<=1.10'
The upper limit should not be included.

2017-01-07 08:16 UTC, webknjaz approved these changes

2017-01-07 09:46 UTC, merged