Feature/testing container in travis ci
kpi-web-guild/django-girls-blog-DrEdi pull request #24
Opened 2017-01-25 19:56 UTC by DrEdi

Create script for run vagga container on TravisCI server

2017-01-25 22:02 UTC, webknjaz requested changes

2017-01-25 22:02 UTC, webknjaz commented on .travis.yml
> +  - vagga test
You don't have to use sequence for a single command.

2017-01-25 22:02 UTC, webknjaz commented on requirements-test.txt
> +setuptools==34.0.2
Normal python installation usually contains setuptools, so this is only needed for vagga env. Please remove it from this file and add to vagga config

2017-01-25 22:02 UTC, webknjaz commented on vagga.yaml
> +      - !BuildDeps
You don't need to declare runtime `!Install` dependencies as `!BuildDeps` as they are available during build as well

2017-01-25 22:02 UTC, webknjaz commented on vagga.yaml
> +      - !Install
Please move this section up to `!BuildDeps` to avoid situation of installing python packages using `git+git://` URL when `git` is not installed yet.

2017-01-25 22:02 UTC, webknjaz commented on vagga.yaml
> +      - !Ubuntu xenial
`Alpine` would work just fine and it will be built faster as it's lightweight.

2017-01-25 22:02 UTC, webknjaz commented on vagga.yaml
> +    run: pre-commit run --all-files
please expose separate `vagga pre-commit` command using `exec` syntax (`run` value is a sequeance)

2017-01-25 23:29 UTC, DrEdi commented on vagga.yaml
> +      - !Ubuntu xenial
Nope. This code is properly works with `Ubunty xenial`, but it always fails with` Alpine`.

2017-01-26 08:13 UTC, webknjaz requested changes

2017-01-26 08:13 UTC, webknjaz commented on vagga.yaml
> +      - !Ubuntu xenial
Why?

2017-01-26 08:13 UTC, webknjaz commented on vagga.yaml
> +  pre-commit: !Command
Where's `test` command?

2017-01-26 08:13 UTC, webknjaz commented on .travis.yml
> +script: vagga pre-commit --all-files
Why did you change this?

2017-01-26 11:52 UTC, DrEdi commented on vagga.yaml
> +      - !Ubuntu xenial
`[Errno 95] Not supported: '/tmp/pip-u800vb8q-build/testing/resources/working_symlink'")]`
End there're many many other with code 95

2017-01-26 11:57 UTC, webknjaz commented on vagga.yaml
> +      - !Ubuntu xenial
And what does it mean? Any detail?

2017-01-26 12:09 UTC, DrEdi commented on vagga.yaml
> +      - !Ubuntu xenial
'An unexpected error has occurred: CalledProcessError: Command: ('/root/.pre-commit/reponf39kcdj/py_env-default/bin/python3.5', '/root/.pre-commit/reponf39kcdj/py_env-default/bin/pip', 'install', '.')
Return code: 2
Expected return code: 0
'
Huge list of [Errno 95]. Then command failed
I've noticed before that some commands do not run under all OS

2017-01-26 18:25 UTC, webknjaz commented on vagga.yaml
> +      - !Ubuntu xenial
Can we improve/fix this?

2017-01-26 20:06 UTC, DrEdi commented on vagga.yaml
> +      - !Ubuntu xenial
I tried some variants. This is not depends on version of alpine. First time I thought that maybe v3.4 of Alpine may be a bit deprecated - after I tried it with v3.5 - result was the same.I also installed it under Ubuntu trusty  and it works. 
I can be wrong but I think Ubuntu has some packages that does not have Alpine, that's why we have trouble with it...

2017-01-27 10:41 UTC, webknjaz commented on vagga.yaml
> +      - !Ubuntu xenial
I'm gonna dig into it myself.
![](http://www.quickmeme.com/img/e7/e7633bedf897bb24ce668ac9c5df6bf88a58ff7e114d27606a756f4c4888a3f1.jpg)

2017-01-27 11:10 UTC, DrEdi commented on vagga.yaml
> +      - !Ubuntu xenial
eeee, memes)

2017-01-27 11:41 UTC, webknjaz commented on vagga.yaml
> +      - !Ubuntu xenial
Alright, it looks failing somewhere inside of `shutil.copytree()`'s system calls, which are file permission/type checks. I think we can leave ubuntu here.

2017-01-27 11:41 UTC, webknjaz approved these changes

2017-01-27 22:14 UTC, merged