Add TravisCi integrations
kpi-web-guild/django-girls-blog-DrEdi pull request #5
Opened 2016-12-09 20:52 UTC by DrEdi

Add info to file .travis.yml
language: python
python: 3.5
cache: pip
before_install: pip install -U pre-commit
script: pre-commit run --all-files

2016-12-09 22:43 UTC, webknjaz requested changes
You have to fix the files, so that Travis CI build won't be failing. I guess you also forgot to install pre-commit for your local repo with command `pre-commit install`. Try doing this and the checks will also run locally.

2016-12-09 22:43 UTC, webknjaz commented on README.md
> +https://travis-ci.org/kpi-web-guild/django-girls-blog-DrEdi.svg?branch=master
There's a markdown version of the button showing image and making it a link. Use it

2016-12-10 16:03 UTC, webknjaz requested changes

2016-12-10 16:03 UTC, webknjaz commented on README.md
> +[![Build Status](https://travis-ci.org/kpi-web-guild/django-girls-blog-DrEdi.svg?branch=feature%2Ftravis-ci-integration)](https://travis-ci.org/kpi-web-guild/django-girls-blog-DrEdi)
It is common to target `master` branch in a CI badge, please change this :)

2016-12-10 17:00 UTC, DrEdi commented on README.md
> +[![Build Status](https://travis-ci.org/kpi-web-guild/django-girls-blog-DrEdi.svg?branch=feature%2Ftravis-ci-integration)](https://travis-ci.org/kpi-web-guild/django-girls-blog-DrEdi)
Do not really understand what's wrong.
I had to do this from master, right?
But when I just wanted to fix it(add it in master, after come to `feature/travis-ci-integration` and push it git said that 'Everything is up-to-date'

2016-12-11 15:29 UTC, webknjaz commented on README.md
> +[![Build Status](https://travis-ci.org/kpi-web-guild/django-girls-blog-DrEdi.svg?branch=feature%2Ftravis-ci-integration)](https://travis-ci.org/kpi-web-guild/django-girls-blog-DrEdi)
`?branch=master`

2016-12-11 15:30 UTC, webknjaz requested changes

2016-12-11 15:30 UTC, webknjaz commented on README.md
> -# django-girls-blog-DrEdi
Add badge for `master` branch set in the URL

2016-12-11 15:40 UTC, webknjaz commented
Please re-check [common commit practices](https://github.com/kpi-web-guild/django-girls-blog-DrEdi/pull/3#issuecomment-265715633). Also, please read info about doing squash via `git rebase --interactive`, so that you could rewrite your feature branches and make their history easy-to-read and well-understandable.

2016-12-11 17:13 UTC, webknjaz approved these changes

2016-12-11 17:18 UTC, merged