Create first Django Project
kpi-web-guild/django-girls-blog-DrEdi pull request #6
Opened 2016-12-14 15:08 UTC by DrEdi

- Create first application for blog
- Add some templates
- Add urls

2016-12-14 15:11 UTC, DrEdi commented
Ohhh
I hoped that `SKIP=flake8,pep257 git commit` have to work

2016-12-14 16:21 UTC, DrEdi commented
Ok, I really don't have idea why it works on my local but fails here

2016-12-14 21:00 UTC, webknjaz commented
I would rebase it on top of master before merging instead of creating merge commits :)
Regarding `exclude`.. you have to use a kind of regular expression in this option's value

2016-12-14 21:30 UTC, webknjaz requested changes
Could you please try using an array for `exclude`? If this won't work, use regexp.
Please also note that generally it is not required to wrap strings with quotes in YAML.

2016-12-14 21:30 UTC, webknjaz commented on .pre-commit-config.yaml
> +      exclude: '[main/, manage.py, blog/]'
AFAIR this should be a regexp string

2016-12-14 21:30 UTC, webknjaz commented on .pre-commit-config.yaml
> +      # args: [--max-line-length=120]
Why did you comment this out?

2016-12-14 21:30 UTC, webknjaz commented on README.md
> +# django-girls-blog-DrEdi
This change looks pointless.
(Unless forced by pre-commit hooks.)

2016-12-14 21:53 UTC, webknjaz requested changes

2016-12-14 21:53 UTC, webknjaz commented on main/templates/main/index.html
> +    <div>
Indentation of for-loop start, div-block and for-loop end is broken here.

2016-12-14 21:53 UTC, webknjaz commented on main/templates/main/index.html
> +	<title>Main</title>
Normally you'd want to use spaces for indentation

2016-12-14 21:53 UTC, webknjaz commented on main/templates/main/index.html
> +        <p>{{ post.text|linebreaksbr }}</p>
filter-pipes are normally wrapped with spaces

2016-12-14 21:53 UTC, webknjaz commented on main/models.py
> +	author = models.ForeignKey('auth.User')
Please use spaces for indentation

2016-12-14 21:53 UTC, webknjaz commented on README.md
> +
This addition is pointless

2016-12-14 21:53 UTC, webknjaz commented on .pre-commit-config.yaml
> +      # args: [--max-line-length=120]
Feel free to use increased value of max-line-length option

2016-12-14 21:53 UTC, webknjaz commented on .pre-commit-config.yaml
> +      exclude: '[main/, manage.py, blog/]'
You **must not** exclude the actual src. You may only ignore db migrations.

2016-12-14 21:53 UTC, webknjaz commented on .pre-commit-config.yaml
> +      exclude: '[main/, manage.py, blog/]'
Add `remove-tabs` to hooks. And see my comment above regarding excludes.

2016-12-15 21:23 UTC, webknjaz requested changes

2016-12-15 21:23 UTC, webknjaz commented on main/templates/main/base.html
> +            </div>
The indentation is odd here, plz fix

2016-12-15 21:23 UTC, webknjaz commented on main/templates/main/base.html
> +<div class="content container">
Why did you reduce indentation of this block? Please be consistent

2016-12-15 21:23 UTC, webknjaz commented on .pre-commit-config.yaml
> +# - repo: https://github.com/FalconSocial/pre-commit-mirrors-pep257
I want you to have this hook enabled

2016-12-15 21:23 UTC, webknjaz commented on manage.py
> +            import django
You may add `  # noqa: F401` comment in the end of this line to make flake8 not raise this error here.

2016-12-15 21:23 UTC, webknjaz commented on main/tests.py
> +from django.test import TestCase
You may comment it out for now.

2016-12-15 22:13 UTC, DrEdi commented
Everything was Ok when I commited in my local machine.
Could we marge it when I fix all the files and only after start to deploy in new branch?

2016-12-16 18:29 UTC, webknjaz commented
Merge will be available once you fix all the dips and tests will pass.

2016-12-17 14:31 UTC, webknjaz requested changes
You have committed your local database, you have to remove it from the repo.

2016-12-17 14:31 UTC, webknjaz commented on .pre-commit-config.yaml
> +      args: [--ignore=D203]
Why did you disable this rule? 
Here's what [the doc states about D203](http://pep257.readthedocs.io/en/latest/error_codes.html):
```
1 blank line required before class docstring
```

2016-12-17 14:31 UTC, webknjaz commented on blog/__init__.py
> +"""Do not write anything here."""
This is not a docstring as it doesn't describe the module's purpose. In fact, it's not even required anymore for Python 3 envs.

2016-12-17 14:31 UTC, webknjaz commented on blog/settings.py
> +Django settings for blog project.
I would leave just this line. Information below isn't particularly helpful or useful.

2016-12-17 14:31 UTC, webknjaz commented on blog/urls.py
> +The `urlpatterns` list routes URLs to views. For more information please see:
Again, this is useful when you first start working with django, but then it's a pointless noise you don't want to keep in your project.

2016-12-17 14:31 UTC, webknjaz commented on blog/wsgi.py
> +It exposes the WSGI callable as a module-level variable named ``application``.
The same comment as above applies here.

2016-12-17 14:31 UTC, webknjaz commented on main/__init__.py
> +"""Do not write anything here."""
This is pointless.

2016-12-17 14:31 UTC, webknjaz commented on main/admin.py
> +"""Admin panel code is here."""
Please do not write useless descriptions stating obvious things like "the second line in this module starts with 'f'". Try taking point of view of a stranger looking at the module his first time and trying to figure out what's going on here.
Write a high-level description of what is the purpose of this module.

2016-12-17 14:31 UTC, webknjaz commented on .gitignore
> +.idea/
Good catch, you also need to ignore SQLite database data file.

2016-12-17 14:31 UTC, webknjaz commented on main/apps.py
> +"""Apps are here."""
What apps?

2016-12-17 14:31 UTC, webknjaz commented on main/models.py
> +"""All models are here."""
What for?

2016-12-17 14:31 UTC, webknjaz commented on main/models.py
> +    """Model that represent post in our blog."""
represent`s`. Mind your grammar :)

2016-12-17 14:31 UTC, webknjaz commented on main/models.py
> +        """Return title of post."""
No. Make title represent instance when interpolating into str

2016-12-17 14:31 UTC, webknjaz commented on main/templates/main/index.html
> +            <h1><a href="post/{{ post.pk }}/">{{ post.title }}</a></h1>
Shouldn't you use `{% url %}` tag here?

2016-12-17 14:31 UTC, webknjaz commented on main/urls.py
> +"""Urls are here."""
Which URLs? Point the difference south the other similar module.

2016-12-17 14:31 UTC, webknjaz commented on main/views.py
> +# Create your views here.
You don't need this comment, do you?

2016-12-17 14:31 UTC, webknjaz commented on main/views.py
> +    """Show info about one post user choosed."""
*Nit: you have chosen

2016-12-17 14:31 UTC, webknjaz commented on manage.py
> +"""Main file for manage your project."""
One ring to rule them all :)

2016-12-17 16:29 UTC, DrEdi commented on .pre-commit-config.yaml
> +      args: [--ignore=D203]
But there's another one `D211 No blank lines allowed before class docstring` :)
I had a conflict

2016-12-17 16:34 UTC, webknjaz commented on .pre-commit-config.yaml
> +      args: [--ignore=D203]
Oh I see, in such cases, when it is not obvious why do you do something it is a good practice to write a comment and explain why did you do this. Otherwise it the future someone may try "fixing"/removing it just because they think it's not how things should be working.

2016-12-18 00:26 UTC, webknjaz approved these changes

2016-12-18 09:19 UTC, merged