Feature/extensions
kpi-web-guild/django-girls-blog-DrEdi pull request #7
Opened 2016-12-20 12:59 UTC by DrEdi

2016-12-20 14:12 UTC, webknjaz commented
Name the PR properly

2016-12-20 15:03 UTC, DrEdi commented
Done :+1:

2016-12-20 15:06 UTC, webknjaz requested changes
Please make your PR look awesome

2016-12-20 15:06 UTC, webknjaz commented on blog/settings.py
> +    from .local_settings import BASE_DIR, DATABASES, DEBUG  # noqa: F401
You don't need the `noqa` comment anymore

2016-12-20 15:06 UTC, webknjaz commented on main/models.py
> +        """Return comment text."""
I see that it returns comment's text field value. It's stated right on the next line. Write something useful here instead. Why is this method needed at all?

2016-12-20 15:06 UTC, webknjaz commented on main/models.py
> +        """Return comment text."""
I would write `Render Comment instance as it's text by default when stringifying`

2016-12-20 15:06 UTC, webknjaz commented on main/templates/main/post_draft_list.html
> +            <p>{{ post.text|truncatechars:200 }}</p>
It is common to wrap pipe with spaces.

2016-12-20 15:06 UTC, webknjaz commented on main/views.py
> +    """If someone want to create new comment he/she get this view."""
In English combo `he/she` is often referred to as `them`.
P.S. `want` -> `wants`

2016-12-20 15:06 UTC, webknjaz commented on main/views.py
> +            post = form.save(commit=False)
Nit: in future I would encapsulate this into a method.

2016-12-20 15:12 UTC, DrEdi commented on blog/settings.py
> +    from .local_settings import BASE_DIR, DATABASES, DEBUG  # noqa: F401
There is one problem without `noqa`:
`blog/settings.py:128:5: F401 '.local_settings.DEBUG' imported but unused`

2016-12-20 16:02 UTC, webknjaz commented
What are the extensions

2016-12-20 16:10 UTC, webknjaz requested changes

2016-12-20 16:10 UTC, webknjaz commented on main/models.py
> +        """Render Comment instance as it's text by default when stringifying."""
`it's` -> `its`

2016-12-20 16:10 UTC, webknjaz commented on blog/settings.py
> -        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
I would move this to `local_settings` instead of wiping completely

2016-12-20 16:10 UTC, webknjaz commented on blog/settings.py
> +        'ENGINE': 'django.db.backends.postgresql_psycopg2',
Why do you even need this? You completely replace `DATABASES['default']` below

2016-12-20 16:10 UTC, webknjaz commented on blog/settings.py
> +    from .local_settings import BASE_DIR, DATABASES, DEBUG  # noqa: F401
ok

2016-12-20 16:10 UTC, webknjaz commented on main/forms.py
> +"""This module is for python forms."""
Oh really? What is this supposed to mean?

2016-12-20 16:10 UTC, webknjaz commented on main/models.py
> +        """Render Comment instance as it's text by default when stringifying."""
`it's` -> `its`

2016-12-20 16:51 UTC, DrEdi commented on blog/settings.py
> -        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
This is there
But `local_settings` are ignored by .gitignore file

2016-12-20 18:44 UTC, webknjaz requested changes

2016-12-20 18:44 UTC, webknjaz commented on main/forms.py
> +"""
Оце виглядає як пропаганда джанго, а не опис призначення модуля.
Ось як я б це записав: `This module keeps the collection of form declarations representing HTML forms binded to data in the DB`.
На відміну від твого варіанту, тут є чітко окреслене призначення модуля і опис його вмісту, без реклами джанго і смс :)

2016-12-20 18:44 UTC, webknjaz commented on main/models.py
>          This is useful if you need to get info only about title of Post object
This is a lie! If I need a title of post I'll use `Post.title` explicitly. See Zen of Python (PEP 20): **Explicit is better than implicit**.

You should've stated that this is used when rendering model instance as a string.

2016-12-20 18:44 UTC, webknjaz commented on blog/settings.py
> +DATABASES['default'] = dj_database_url.config()
It's worth declaring right in that dict above.

2016-12-20 23:27 UTC, webknjaz requested changes

2016-12-20 23:27 UTC, webknjaz commented on blog/settings.py
> +DATABASES = {
Why did you paste it here instead of replacing the one above?

2016-12-21 17:26 UTC, webknjaz commented on requirements.txt
> +aspy.yaml==0.2.2
Are all of these dependencies really needed?

2016-12-21 17:28 UTC, webknjaz commented on requirements.txt
> +aspy.yaml==0.2.2
Could you please split ones needed always from those needed in production?

2016-12-21 17:29 UTC, webknjaz commented on requirements.txt
> +aspy.yaml==0.2.2
You may check the way it works in @pavlenk0's [repo](https://github.com/kpi-web-guild/django-girls-blog-pavlenk0/blob/master/test_requirements.txt)

2016-12-21 17:30 UTC, webknjaz approved these changes

2016-12-21 17:30 UTC, DrEdi commented on requirements.txt
> +aspy.yaml==0.2.2
I'm not sure,
I did it from virt environment, so I thought all from there are important

2016-12-21 19:14 UTC, webknjaz commented on requirements.txt
> +aspy.yaml==0.2.2
Some of them are dependencies of others and do not need to be declared explicitly. It's a mess.

2016-12-21 19:18 UTC, DrEdi commented on requirements.txt
> +aspy.yaml==0.2.2
One moment, I'll fix it!

2016-12-22 11:50 UTC, merged

2016-12-22 11:51 UTC, webknjaz commented on blog/settings.py
> +LOGIN_REDIRECT_URL = '/'
I would add a new line next to this one

2016-12-22 11:51 UTC, webknjaz commented on main/models.py
> +    approved_comment = models.BooleanField(default=False)
Nit: it would be better to call this column `is_approved`

2016-12-22 11:51 UTC, webknjaz commented on main/models.py
> +        return self.comments.filter(approved_comment=True)
I would add a method to the `Comment` model to encapsulate filtering in there.

2016-12-22 11:51 UTC, webknjaz commented on main/models.py
> +        """Approving comments. Use for moderating."""
`Approving` is Present Continuous Tense. Write it in imperative mode. Also you didn't describe an action this method does.

2016-12-22 12:02 UTC, DrEdi commented on main/models.py
> +    approved_comment = models.BooleanField(default=False)
Oooops, sorry, I thought I can merge it...
I'll fix it next time